Sanchitbajaj02/palettegram

- CONTRIBUTING.md
- README.md
- docs/appwrite.md
- docs/git.md
- docs/setup.md
Added some basic docs regarding github setup , project setup, appwrite setup, contrubution etc. 
Docs left:
Future works, Frontend explaination, backend explanation, PR title checker explanation.
> docs: added some basic docs. 

- src/App.jsx
- src/DB/api.js
- src/components/Posts.jsx
- src/components/SinglePost.jsx
- src/components/UserPosts.jsx
- src/components/UserProfile.jsx
- yarn.lock
Tasks left for user Profile:
Display ALl posts with user Information,
Improve UI
display proper post data
> feat: added user profile API

- src/DB/api.js
- src/components/PostProfilePage.jsx
- src/components/Posts.jsx
- src/components/SinglePost.jsx
- src/components/UserProfile.jsx
- Added User Like
- Fixed User Profile page bug
- Fixed Single Post Page bug
- UI improvement of profile page with data display in cards
- Creation of new post with palette
Video of output:
[Screencast from 14-06-23 08:58:31 PM IST.webm](https://github.com/Sanchitbajaj02/palettegram/assets/72390769/b5b0d6e5-0f3b-407d-834d-67fd126506bf)
> feat: added user like

- src/DB/api.js
- src/DB/appwrite.config.js
- src/components/CreatePost.jsx
- src/components/PostProfilePage.jsx
- src/components/SinglePost.jsx
Added image upload feature while creating a new post, and user can remove post too before posting.
Tasks remaining:
-adding a ui to show a delete button on post hover
Video:
[Screencast from 14-06-23 11:17:06 PM IST.webm](https://github.com/Sanchitbajaj02/palettegram/assets/72390769/69ce20aa-a924-40ef-9791-91c38921ebc6)
> feat: added image upload in creating a new post

- README.md
Readme enhanced so that contributors can better interpret with it
> docs: readme update with enhanced grammar

- src/app/layout.tsx
- src/backend/auth.api.ts
- src/components/pages/auth/register/index.tsx
- src/components/pages/auth/verification/index.tsx
- src/components/pages/home/index.tsx
- src/helper/toastify.ts
- src/middleware.ts
- Previously the toast is not showing because the toast container component is not configured properly.
- verify system was not working because the params of `/verify` were blocked.
- The status check for register and login button were independent of login status, not it is dependent with the states
> fix: verify status working and updated db system along with toastify working

- README.md
Added an intro image and included the discord community link
> Docs refactor

- src/backend/auth.api.ts
- src/backend/posts.api.ts
- src/components/core/createPost/index.tsx
- src/components/core/navbar/index.tsx
- src/components/core/posts/SinglePost.tsx
- src/components/pages/auth/login/index.tsx
- src/components/pages/auth/register/index.tsx
- src/components/pages/auth/verification/index.tsx
- src/components/pages/home/index.tsx
- src/redux/reducers/authReducer.ts
- src/types/index.d.ts
> fix: localstorage dependency removed

- src/components/core/buttons/index.tsx
- src/components/core/navbar/index.tsx
- src/components/core/themeButton/index.tsx
- tailwind.config.js
style: #118 
Improved the UI of buttons in i.e. added a hover effect 
https://github.com/Sanchitbajaj02/palettegram/assets/112563353/022dbf6d-c7c8-4ddc-b3ac-57bc94321a65
> style: improving the ui of buttons #118

- src/components/pages/home/index.tsx
feat: Added profile button on navbar
Closes #120 
I have added a user profile button on navbar so that user can visit his profile directly. It will be displayed to logged in user only.
> feat: added-profile-button-on-home-page

- .github/labeler.yml
- SECURITY.md
- docs/appwrite.md
- package.json
- src/components/pages/auth/login/index.tsx
- yarn.lock
Related issue: #128 
- Upgraded the Next.js version
- Added the sharp library for image optimisation
- Updated the security.md and appwrite.md for open source contributors to follow.
- fix the use state for production
> chore: Optimization for smooth production

- src/components/core/navbar/index.tsx
- src/components/core/posts/SinglePost.tsx
Issue #93 Bug Bookmark does not working properly
To solve this I did the following steps:
- In the `navbar/index.tsx` file at line no `55` handle bookmark reference error.
- In the `SinglePost.tsx` file inside the `handleUpdateBookmark` function removed `accountId` Params.
- At line `65` update the condition to check whether the bookmark exists or not for the currently logged user.
- At line `66` updated condition from the `reduce` method to `some`. This will check current bookmark exists or not inside the current bookmark array and return true or false accordingly.
- I also added a type check for the bookmark object.
> fix: Issue #93 Bookmark does not working properly

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/styles.yml
- src/app/[others]/page.tsx
- src/app/layout.tsx
- src/components/core/posts/SinglePost.tsx
changes:
- docs: yml fix for SWOC
- refactor: minor refactoring in files
> docs: fix the docs and fix minor changes

- src/backend/posts.api.ts
- src/components/core/createPost/index.tsx
- src/components/core/posts/index.tsx
- src/components/pages/user/userPosts/index.tsx
- src/redux/reducers/postsReducer.ts
- src/types/index.d.ts
Fix: #115 
User can now **delete** his/her post by going to profile and click on small dustbin icon
> feat: added delete post feature

- src/components/pages/contact/index.tsx
Fix #205 
matched the contact page ui with the one used in register/login page
> fix: matched the contact page ui with the one used in register/login page

- src/components/core/posts/SinglePost.tsx
#153 
Added a Share feature using WebShare API
> feat: Added share button

- src/components/core/navbar/index.tsx
- src/components/pages/contact/index.tsx
Fix #206 
Refactor navbar component to conditionally render user links and logout button
not logged in:
logged in:
> fix: Refactor navbar component to conditionally render user links and logout button 

- src/redux/reducers/authReducer.ts
accountID or userId will be cleared or destroyed
> fix: logout functionality bug

- appwrite-gen/schema.json
- package.json
- src/components/core/colorPicker/index.tsx
- src/components/core/createPost/index.tsx
- src/components/core/posts/SinglePost.tsx
- src/types/index.d.ts
Fix issue #98 Feat: Color picker generator (Work with Admin)
In order to implement this feature did following steps:
- Changes `Schema.json` to store string of colors  in DB.
- Added new package `react-colorful` for color picker.
- Made changes in `colorpicker/index.tsx` file to implement color palette with color picker.
- Made changes in `createPost/index.tsx` file to implement post logic define default color for pallete and handle logic for creating post on db.
- `SinglePost.tsx` written logic to show the palette. Also added copy functionality.
During Post creation:
Palette Post:
Copy color from post by clicking on it:
> feat: Color picker generator (Work with Admin) issue #98

- src/components/core/footer/index.tsx
- yarn.lock
- added a responsive and detailed footer section
> feat: add detailed footer section

- src/app/feed/loading.tsx
- src/components/core/navbar/index.tsx
- src/components/pages/feed/index.tsx
Fix : #229 
convert feed UI from 3 col to 2, I also made change in loading skeleton of feed UI to make feed more consistent
> refactor: change feed UI and navbar

- src/app/feed/page.tsx
- src/components/core/themeButton/index.tsx
- src/components/pages/home/index.tsx
- yarn.lock
fixes #270 
Fixes the theme icon
> fix: theme switch loading fix and home page animation fix
